FROM mcr.microsoft.com/dotnet/sdk:2.1 AS build-env

COPY ./libs /app/libs
COPY ./modules/sample_module/*.csproj /app/modules/sample_module/
COPY ./modules/sample_module /app/modules/sample_module

WORKDIR /app/modules/sample_module
RUN dotnet restore
RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/runtime:2.1-stretch-slim
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "sample_module.dll"]