FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2022 AS build-env

COPY ./libs /app/libs
COPY ./modules/sample_module/*.csproj /app/modules/sample_module/
COPY ./modules/sample_module /app/modules/sample_module

WORKDIR /app/modules/sample_module
RUN dotnet restore
RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/runtime:8.0-nanoserver-ltsc2022
WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "sample_module.dll"]