# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/python
pr:
  branches:
    include:
    - main 
    - refs/heads/main 

# trigger: none

jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    strategy:
      matrix:
        Python36:
          python.version: "3.6"
          TOXENV: "py36"
        Python37:
          python.version: "3.7"
          TOXENV: "py37"
        Python38:
          python.version: "3.8"
          TOXENV: "py38"
        Python39:
          python.version: "3.9"
          TOXENV: "py39"
      maxParallel: 1
    steps:
      - template: win32/continuous-build-win32.yml

  # - job: MacOS
  #   pool:
  #     vmImage: macOS-10.13
  #   strategy:
  #     matrix:
  #       Python36:
  #         python.version: "3.6"
  #         TOXENV: "py36"
  #       Python37:
  #         python.version: "3.7"
  #         TOXENV: "py37"
  #      Python38:
  #        python.version: "3.8"
  #        TOXENV: "py38"
  #      Python39:
  #        python.version: "3.9"
  #        TOXENV: "py39"
  #     maxParallel: 1
  #   steps:
  #     - template: darwin/continuous-build-darwin.yml

  - job: Ubuntu18
    pool:
      vmImage: ubuntu-18.04
    strategy:
      matrix:
        Python36:
          python.version: "3.6"
          TOXENV: "py36"
        Python37:
          python.version: "3.7"
          TOXENV: "py37"
        Python38:
          python.version: "3.8"
          TOXENV: "py38"
        Python39:
          python.version: "3.9"
          TOXENV: "py39"
      maxParallel: 1
    steps:
      - template: linux/continuous-build-linux.yml

  - job: Ubuntu20
    pool:
      vmImage: ubuntu-20.04
    strategy:
      matrix:
        Python36:
          python.version: "3.6"
          TOXENV: "py36"
        Python37:
          python.version: "3.7"
          TOXENV: "py37"
        Python38:
          python.version: "3.8"
          TOXENV: "py38"
        Python39:
          python.version: "3.9"
          TOXENV: "py39"
      maxParallel: 1
    steps:
      - template: linux/continuous-build-linux.yml
