
parameters:
  - name: VersionType
    displayName: "Select version type"
    type: string
    default: minor
    values:
    - none
    - minor
    - major
  - name: BuildMode
    displayName: 'Build Mode'
    type: string
    default: test
    values:
      - test
      - prod

pool:
  vmImage: ubuntu-latest


steps:
- task: UsePythonVersion@0
  displayName:  "Install Python"
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  displayName: "Install Python packages"
  inputs:
    targetType: 'inline'
    script: |
      pip install bumpversion
      pip install tox
      pip install twine
      sudo apt-get install gcc libpq-dev -y
      sudo apt-get install python-dev  python-pip -y
      sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
      pip3 install wheel

- task: Bash@3
  displayName: "Update Version using bumpversion"
  inputs:
    targetType: 'inline'
    script: |
      echo "Build mode: ${{ parameters.BuildMode }}"
      if [ "${{ parameters.BuildMode }}" = "prod" ]; then
              bumpversion "${{ parameters.VersionType }}"
          else
              bumpversion "${{ parameters.VersionType }}" --no-commit --no-tag --allow-dirty
          fi

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       echo -e "\n===== Preventive cleanup"
#           rm __pycache__ -rf
#           rm .pytest_cache -rf
#           rm .tox -rf
#           rm .pytest_cache -rf
#           rm tests/__pycache__ -rf
      
#           echo -e "\n===== Running Tox"
#           tox

- task: Bash@3
  displayName: "Update AIKey"
  inputs:
    targetType: 'inline'
    script: 'sed -i "/__AIkey__/c __AIkey__ = ''$(AIKEY)''" ./iotedgedev/__init__.py'

- task: Bash@3
  displayName: "Build wheel"
  inputs:
    targetType: 'inline'
    script: 'python setup.py bdist_wheel'

- task: Bash@3
  displayName: "Revert AIKey to Original"
  inputs:
    targetType: 'inline'
    script: 'sed -i "/__AIkey__/c __AIkey__ = ''$(TEST_AIKEY)''" ./iotedgedev/__init__.py'

- task: AzureKeyVault@2
  displayName: 'Azure Key Vault: azure-iot-edgetools-kv'
  inputs:
    azureSubscription: 'Azure IoT DDE team subscription (377c3343-75bb-4244-98a3-0fb84a830c4b)-IoTEdgeDev'
    KeyVaultName: 'azure-iot-edgetools-kv'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      VERSION=$(cat ./iotedgedev/__init__.py | grep '__version__' | grep -oP "'\K[^']+")
      PYPI=$([ "${{ parameters.BuildMode }}" = "prod" ] && echo "pypitest" || echo "pypitest")
      twine upload -r ${PYPI} "dist/iotedgedev-${VERSION}-py3-none-any.whl" -u "$(pypiusername)" -p "$(aziotedge)" --repository-url "$(pypirepourl)"

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'vikas0212git'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    tagPattern: '^v?[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$'
    releaseNotesSource: 'input'
    isPreRelease: true
    addChangeLog: false

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'vikas0212git'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    tagPattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    releaseNotesSource: 'input'
    addChangeLog: false

- task: Bash@3
  displayName: "Verify wheel"
  inputs:
    targetType: 'inline'
    script: 'pip install --upgrade iotedgedev && iotedgedev --version'

- task: Bash@3
  displayName: "Buld Docker image"
  inputs:
    targetType: 'inline'
    script: './build-docker.sh iotedgetoolscontainerregistry.azurecr.io/public/iotedge/iotedgedev linux'
    workingDirectory: 'docker/tool'

- task: Bash@3
  displayName: "Test local Docker image"
  inputs:
    targetType: 'inline'
    script: |
       VERSION=$(cat ./iotedgedev/__init__.py | grep '__version__' | grep -oP "'\K[^']+")
       mkdir /mnt/iotedge
       docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/iotedge:/home/iotedge iotedgetoolscontainerregistry.azurecr.io/public/iotedge/iotedgedev:${VERSION}
    workingDirectory: 'docker/tool'

- task: Bash@3
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  displayName: "Push docker image to acr"
  inputs:
    targetType: 'inline'
    script: |
       VERSION=$(cat ../../iotedgedev/__init__.py | grep '__version__' | grep -oP "'\K[^']+")
       docker login iotedgetoolscontainerregistry.azurecr.io -u IotEdgeToolsContainerRegistry -p $(acr_password)
       ./push-docker.sh ${VERSION}
    workingDirectory: 'docker/tool'

- task: Bash@3
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  displayName: "Test last uploaded Docker image"
  inputs:
    targetType: 'inline'
    script: |
      docker pull mcr.microsoft.com/iotedge/iotedgedev
      docker run -ti --rm  mcr.microsoft.com/iotedge/iotedgedev 
      iotedgedev --version    
    workingDirectory: 'docker/tool'