FROM mcr.microsoft.com/dotnet/sdk:2.1 AS build-env

COPY ./libs /app/libs
COPY ./sample_module_2/*.csproj /app/sample_module_2/
COPY ./sample_module_2 /app/sample_module_2

WORKDIR /app/sample_module_2
RUN dotnet restore
RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/runtime:2.1-nanoserver-1809
WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "sample_module_2.dll"]