version: 2
variables: 
  - &workdir
    /tmp/circleci
  - &branchignore
    ignore: [noci, gh-pages]
  - &buildtest
      - image: dtzar/iotedgedev:tmp
  - &builddocker
      - image: docker:18
  - &run-dockerbuild
    name: Build and push Docker Image
    command: |
      #tar -cvf $CIRCLE_WORKING_DIRECTORY/docker/linux/files.tar.gz -C . requirements_dev.txt setup.py HISTORY.rst
      ls /tmp/circleci/docker/docker
      docker build -f $CIRCLE_WORKING_DIRECTORY/docker/docker/linux/Dockerfile --build-arg VCS_REF=$CIRCLE_SHA1 --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:circle -t $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest $CIRCLE_WORKING_DIRECTORY/docker/docker
      if [[ ((`echo $CIRCLE_JOB | grep -c "dockerimagebuildpublish"` > 0))]]; then 
        echo "Push to registry since it's the docker build and push job."
        docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASS
        docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG
        docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest
        echo "Pushed image: " $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG " and :latest tag"
      else
        echo "Skip Docker push image since it is not the docker build and publish job."
      fi

jobs:
  toxci:
    working_directory: *workdir
    docker: *buildtest
    steps:
      - checkout
      - run: |
          echo -e 'IOTHUB_CONNECTION_STRING="'$IOTHUB_CONNECTION_STRING'"\nDEVICE_CONNECTION_STRING="'$DEVICE_CONNECTION_STRING'"'> .env
          mkdir -p $CIRCLE_WORKING_DIRECTORY/tmp/docker/linux
          cp $CIRCLE_WORKING_DIRECTORY/docker/linux/Dockerfile $CIRCLE_WORKING_DIRECTORY/tmp/docker/linux
          tar -cvf $CIRCLE_WORKING_DIRECTORY/tmp/docker/files.tar.gz -C . requirements_dev.txt setup.py HISTORY.rst
          #tox
      - persist_to_workspace:
          root: tmp
          paths:
            - docker/*
  dockerimagebuild:
    working_directory: *workdir
    docker: *builddocker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: docker
      - run: *run-dockerbuild
  dockerimagebuildpublish:
    working_directory: *workdir
    docker: *builddocker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: docker
      - run: *run-dockerbuild

workflows:
  version: 2
  azure-iot-edge-dev-tool:
    jobs:
      - toxci:
          filters:
            branches: *branchignore
      - holddocker:
          type: approval
          requires: 
            - toxci
      - dockerimagebuild:
          requires:
            - holddocker
      - holdpublish:
          type: approval
          requires: 
            - toxci
      - dockerimagebuildpublish:
          requires:
            - holdpublish