name: Feature request
description: Suggest an idea for this project.
title: "[FEATURE REQ] <title>"
labels: ["feature", "triage"]

body:
  - type: textarea
    id: background
    attributes:
      label: Description.
      description: What feature would you like to get added? What problem is it solving?
      placeholder: Feature description
    validations:
      required: true
